-- MySQL Script generated by MySQL Workbench
-- Sat Nov  3 11:08:33 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema policymanagementsystem
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema policymanagementsystem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `policymanagementsystem` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `policymanagementsystem` ;

-- -----------------------------------------------------
-- Table `policymanagementsystem`.`company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `policymanagementsystem`.`company` (
  `company_ins_id` VARCHAR(3) NOT NULL,
  `company_name` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`company_ins_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `policymanagementsystem`.`hint`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `policymanagementsystem`.`hint` (
  `hint_id` INT(2) NOT NULL,
  `hint_des` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`hint_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `policymanagementsystem`.`mainuser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `policymanagementsystem`.`mainuser` (
  `user_id` VARCHAR(255) NOT NULL,
  `first_name` VARCHAR(255) NULL DEFAULT NULL,
  `last_name` VARCHAR(255) NULL DEFAULT NULL,
  `dob` DATE NULL DEFAULT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `contact_no` VARCHAR(255) NULL DEFAULT NULL,
  `email_id` VARCHAR(255) NULL DEFAULT NULL,
  `qualification` VARCHAR(255) NULL DEFAULT NULL,
  `gender` VARCHAR(255) NULL DEFAULT NULL,
  `salary` DOUBLE(10,2) NULL DEFAULT NULL,
  `pan_no` VARCHAR(10) NULL DEFAULT NULL,
  `employer_type` VARCHAR(20) NULL DEFAULT NULL,
  `employer` VARCHAR(255) NULL DEFAULT NULL,
  `hint_hint_id` INT(2) NOT NULL,
  `hint_answer` VARCHAR(20) NULL DEFAULT NULL,
  `passcode` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email_id` (`email_id` ASC) VISIBLE,
  UNIQUE INDEX `pan_no` (`pan_no` ASC) VISIBLE,
  INDEX `fk_mainuser_hint_idx` (`hint_hint_id` ASC) VISIBLE,
  CONSTRAINT `fk_mainuser_hint`
    FOREIGN KEY (`hint_hint_id`)
    REFERENCES `policymanagementsystem`.`hint` (`hint_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `policymanagementsystem`.`policy_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `policymanagementsystem`.`policy_table` (
  `policy_id` VARCHAR(11) NOT NULL,
  `company_company_ins_id` VARCHAR(3) NOT NULL,
  `policy_name` VARCHAR(20) NOT NULL,
  `start_date` DATE NOT NULL,
  `duration` INT(4) NULL DEFAULT NULL,
  `initial_deposit` DOUBLE(10,2) NULL DEFAULT NULL,
  `terms_per_year` INT(4) NULL DEFAULT NULL,
  `term_amount` DOUBLE(6,2) NULL DEFAULT NULL,
  `interest` DOUBLE(4,2) NULL DEFAULT NULL,
  PRIMARY KEY (`policy_id`),
  INDEX `fk_policy_table_company1_idx` (`company_company_ins_id` ASC) VISIBLE,
  CONSTRAINT `fk_policy_table_company1`
    FOREIGN KEY (`company_company_ins_id`)
    REFERENCES `policymanagementsystem`.`company` (`company_ins_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `policymanagementsystem`.`policy_payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `policymanagementsystem`.`policy_payment` (
  `bill_id` VARCHAR(20) NOT NULL,
  `bill_date` DATE NOT NULL,
  `paid_amt` DOUBLE(6,2) NULL DEFAULT NULL,
  `fine` DOUBLE(6,2) NULL DEFAULT NULL,
  `due_date` DATE NOT NULL,
  `policy_table_policy_id` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`bill_id`),
  INDEX `fk_policy_payment_policy_table1_idx` (`policy_table_policy_id` ASC) VISIBLE,
  CONSTRAINT `fk_policy_payment_policy_table1`
    FOREIGN KEY (`policy_table_policy_id`)
    REFERENCES `policymanagementsystem`.`policy_table` (`policy_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `policymanagementsystem`.`user_enrolled_policy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `policymanagementsystem`.`user_enrolled_policy` (
  `id` INT(20) NOT NULL AUTO_INCREMENT,
  `mainuser_user_id` VARCHAR(255) NOT NULL,
  `policy_table_policy_id` VARCHAR(11) NOT NULL,
  `enrolled_date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_enrolled_policy_mainuser1_idx` (`mainuser_user_id` ASC) VISIBLE,
  INDEX `fk_user_enrolled_policy_policy_table1_idx` (`policy_table_policy_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_enrolled_policy_mainuser1`
    FOREIGN KEY (`mainuser_user_id`)
    REFERENCES `policymanagementsystem`.`mainuser` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_enrolled_policy_policy_table1`
    FOREIGN KEY (`policy_table_policy_id`)
    REFERENCES `policymanagementsystem`.`policy_table` (`policy_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `policymanagementsystem`.`policy_payment_has_mainuser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `policymanagementsystem`.`policy_payment_has_mainuser` (
  `policy_payment_bill_id` VARCHAR(20) NOT NULL,
  `mainuser_user_id` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`policy_payment_bill_id`, `mainuser_user_id`),
  INDEX `fk_policy_payment_has_mainuser_mainuser1_idx` (`mainuser_user_id` ASC) VISIBLE,
  INDEX `fk_policy_payment_has_mainuser_policy_payment1_idx` (`policy_payment_bill_id` ASC) VISIBLE,
  CONSTRAINT `fk_policy_payment_has_mainuser_policy_payment1`
    FOREIGN KEY (`policy_payment_bill_id`)
    REFERENCES `policymanagementsystem`.`policy_payment` (`bill_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_policy_payment_has_mainuser_mainuser1`
    FOREIGN KEY (`mainuser_user_id`)
    REFERENCES `policymanagementsystem`.`mainuser` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
